import React from 'react';
import { Container, Col, Row } from 'reactstrap';

const ViewAllMatches = props => {
    return (
        <Container>
            <Row>
                <Col sm={{ size: 8, offset: 2 }} md={{ size: 6, offset: 3 }}>
                    <div className="scroll-bar">
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                        <div>
                            SCROLL
                        </div>
                    </div>
                </Col>
            </Row>
        </Container>
    )
}

export default ViewAllMatches